import os
import subprocess
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM
from crewai.tools import tool

# 1. Environment Variables లోడ్ చేయడం
load_dotenv()

# 2. CrewAI సొంత LLM ద్వారా Gemini 1.5 Flash ని కాన్ఫిగర్ చేయడం
llm = LLM(
    model="gemini/gemini-3.5-flash",
    api_key=os.getenv("GEMINI_API_KEY")
)

# 3. Python Code ని రన్ చేసే సరికొత్త Custom Tool
@tool("Python Execution Tool")
def execute_python_code(code: str) -> str:
    """Executes the given Python code in a temporary file and returns the output or error."""
    clean_code = code.replace("```python", "").replace("```", "").strip()
    
    filename = "temp_script.py"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(clean_code)
    
    try:
        result = subprocess.run(
            ["python", filename],
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            return f"SUCCESS:\n{result.stdout}"
        else:
            return f"ERROR:\n{result.stderr}"
    except Exception as e:
        return f"EXECUTION FAILED: {str(e)}"

# 4. AGENTS
coder_agent = Agent(
    role="Senior Python Developer",
    goal="Write accurate Python scripts.",
    backstory="You are an expert Python developer who writes code.",
    verbose=True,
    llm=llm
)

tester_agent = Agent(
    role="Code QA & Debugger",
    goal="Test code execution, capture errors, and iterate until the code runs perfectly.",
    backstory="You run Python code using tools, analyze error outputs, and fix bugs until SUCCESS is achieved.",
    tools=[execute_python_code],
    verbose=True,
    llm=llm
)

# 5. TASKS
task_code = Task(
    description=(
        "Write a Python script that calculates the average of a list of numbers, "
        "but deliberately include a small bug (like dividing by zero when list is empty). "
        "Provide only the Python code."
    ),
    expected_output="Python code script containing a bug.",
    agent=coder_agent
)

task_debug = Task(
    description=(
        "1. Take the Python code generated by the coder.\n"
        "2. Execute it using the Python Execution Tool.\n"
        "3. If an ERROR is returned, rewrite the code to fix it and execute again.\n"
        "4. Repeat until SUCCESS status is achieved."
    ),
    expected_output="Final working Python code and successful output log.",
    agent=tester_agent
)

# 6. CREW WORKFLOW
code_fixer_crew = Crew(
    agents=[coder_agent, tester_agent],
    tasks=[task_code, task_debug],
    process=Process.sequential,
    verbose=True
)

# 7. EXECUTION
if __name__ == "__main__":
    print("🚀 Starting Self-Correction Code Writer Agent...\n")
    result = code_fixer_crew.kickoff()
    print("\n\n================ FINAL OUTPUT ================\n")
    print(result)